package = "guitar.nvim"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "A neovim plugin to aid in writing guitar tablature."
maintainer = "Mike Mehl"
labels = []
license = "MIT"

[dependencies]
busted = "2.2.0-1"
xmlua = "1.2.2-0"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
command = "nvim"
args = ["-l", "lua/guitar/init.lua"]

[build]
type = "builtin"
