local guitar = require("guitar")

describe("add_staff", function()
  setup(function()
    local buf = vim.api.nvim_create_buf(true, false)
    local win = vim.api.nvim_open_win(buf, false, { relative = 'win', row = 10, col = 10, width = 12, height = 12 })
    vim.api.nvim_set_current_win(win)
  end)
  it("is cool lol", function()
    local status, errstr = guitar.add_staff()
    assert(status)
    assert(errstr == nil)
  end)
end)
